# Generated by Django 3.2.23 on 2023-11-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a floor plans', max_length=200)),
                ('summary', models.TextField(help_text='Опишите заявку')),
                ('file', models.FileField(null=True, upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
