# Generated by Django 3.2.23 on 2023-11-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=254, unique=True, verbose_name='Фамилия'),
        ),
    ]
