# Generated by Django 3.2.23 on 2023-11-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20231102_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True, verbose_name='Лoгин')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='Пoчтa')),
                ('password', models.CharField(max_length=254, verbose_name='Пapoль')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пoльзователь')], default='user', max_length=254, verbose_name='Роль')),
            ],
        ),
    ]
